package io.billie.organisations.model

enum class LegalEntityType {
    SOLE_PROPRIETORSHIP,
    PARTNERSHIP,
    LIMITED_LIABILITY_COMPANY,
    S_CORPORATION,
    GENERAL_PARTNERSHIP,
    NONPROFIT_ORGANIZATION,
    C_CORPORATION,
    LIMITED_COMPANY,
    LIMITED_LIABILITY_PARTNERSHIP,
    COOPERATIVE,
    JOINT_VENTURE,
    PRIVATELY_HELD_COMPANY,
    MATRIX_MANAGEMENT,
    LIMITED_LIABILITY_COMPANIES
}
