insert into organisations_schema.countries(country_code, name) VALUES ('AD','Andorra');
insert into organisations_schema.countries(country_code, name) VALUES ('AE','United Arab Emirates');
insert into organisations_schema.countries(country_code, name) VALUES ('AF','Afghanistan');
insert into organisations_schema.countries(country_code, name) VALUES ('AG','Antigua and/or Barbuda');
insert into organisations_schema.countries(country_code, name) VALUES ('AI','Anguilla');
insert into organisations_schema.countries(country_code, name) VALUES ('AL','Albania');
insert into organisations_schema.countries(country_code, name) VALUES ('AM','Armenia');
insert into organisations_schema.countries(country_code, name) VALUES ('AN','Netherlands Antilles');
insert into organisations_schema.countries(country_code, name) VALUES ('AO','Angola');
insert into organisations_schema.countries(country_code, name) VALUES ('AQ','Antarctica');
insert into organisations_schema.countries(country_code, name) VALUES ('AR','Argentina');
insert into organisations_schema.countries(country_code, name) VALUES ('AT','Austria');
insert into organisations_schema.countries(country_code, name) VALUES ('AU','Australia');
insert into organisations_schema.countries(country_code, name) VALUES ('AW','Aruba');
insert into organisations_schema.countries(country_code, name) VALUES ('AZ','Azerbaijan');
insert into organisations_schema.countries(country_code, name) VALUES ('BA','Bosnia and Herzegovina');
insert into organisations_schema.countries(country_code, name) VALUES ('BB','Barbados');
insert into organisations_schema.countries(country_code, name) VALUES ('BD','Bangladesh');
insert into organisations_schema.countries(country_code, name) VALUES ('BE','Belgium');
insert into organisations_schema.countries(country_code, name) VALUES ('BF','Burkina Faso');
insert into organisations_schema.countries(country_code, name) VALUES ('BG','Bulgaria');
insert into organisations_schema.countries(country_code, name) VALUES ('BH','Bahrain');
insert into organisations_schema.countries(country_code, name) VALUES ('BI','Burundi');
insert into organisations_schema.countries(country_code, name) VALUES ('BJ','Benin');
insert into organisations_schema.countries(country_code, name) VALUES ('BM','Bermuda');
insert into organisations_schema.countries(country_code, name) VALUES ('BN','Brunei Darussalam');
insert into organisations_schema.countries(country_code, name) VALUES ('BO','Bolivia');
insert into organisations_schema.countries(country_code, name) VALUES ('BR','Brazil');
insert into organisations_schema.countries(country_code, name) VALUES ('BS','Bahamas');
insert into organisations_schema.countries(country_code, name) VALUES ('BT','Bhutan');
insert into organisations_schema.countries(country_code, name) VALUES ('BV','Bouvet Island');
insert into organisations_schema.countries(country_code, name) VALUES ('BW','Botswana');
insert into organisations_schema.countries(country_code, name) VALUES ('BY','Belarus');
insert into organisations_schema.countries(country_code, name) VALUES ('BZ','Belize');
insert into organisations_schema.countries(country_code, name) VALUES ('CA','Canada');
insert into organisations_schema.countries(country_code, name) VALUES ('CC','Cocos (Keeling) Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('CF','Central African Republic');
insert into organisations_schema.countries(country_code, name) VALUES ('CG','Congo');
insert into organisations_schema.countries(country_code, name) VALUES ('CH','Switzerland');
insert into organisations_schema.countries(country_code, name) VALUES ('CI','Ivory Coast');
insert into organisations_schema.countries(country_code, name) VALUES ('CK','Cook Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('CL','Chile');
insert into organisations_schema.countries(country_code, name) VALUES ('CM','Cameroon');
insert into organisations_schema.countries(country_code, name) VALUES ('CN','China');
insert into organisations_schema.countries(country_code, name) VALUES ('CO','Colombia');
insert into organisations_schema.countries(country_code, name) VALUES ('CR','Costa Rica');
insert into organisations_schema.countries(country_code, name) VALUES ('CU','Cuba');
insert into organisations_schema.countries(country_code, name) VALUES ('CV','Cape Verde');
insert into organisations_schema.countries(country_code, name) VALUES ('CX','Christmas Island');
insert into organisations_schema.countries(country_code, name) VALUES ('CY','Cyprus');
insert into organisations_schema.countries(country_code, name) VALUES ('CZ','Czech Republic');
insert into organisations_schema.countries(country_code, name) VALUES ('DE','Germany');
insert into organisations_schema.countries(country_code, name) VALUES ('DJ','Djibouti');
insert into organisations_schema.countries(country_code, name) VALUES ('DK','Denmark');
insert into organisations_schema.countries(country_code, name) VALUES ('DM','Dominica');
insert into organisations_schema.countries(country_code, name) VALUES ('DO','Dominican Republic');
insert into organisations_schema.countries(country_code, name) VALUES ('DS','American Samoa');
insert into organisations_schema.countries(country_code, name) VALUES ('DZ','Algeria');
insert into organisations_schema.countries(country_code, name) VALUES ('EC','Ecuador');
insert into organisations_schema.countries(country_code, name) VALUES ('EE','Estonia');
insert into organisations_schema.countries(country_code, name) VALUES ('EG','Egypt');
insert into organisations_schema.countries(country_code, name) VALUES ('EH','Western Sahara');
insert into organisations_schema.countries(country_code, name) VALUES ('ER','Eritrea');
insert into organisations_schema.countries(country_code, name) VALUES ('ES','Spain');
insert into organisations_schema.countries(country_code, name) VALUES ('ET','Ethiopia');
insert into organisations_schema.countries(country_code, name) VALUES ('FI','Finland');
insert into organisations_schema.countries(country_code, name) VALUES ('FJ','Fiji');
insert into organisations_schema.countries(country_code, name) VALUES ('FK','Falkland Islands (Malvinas)');
insert into organisations_schema.countries(country_code, name) VALUES ('FM','Micronesia, Federated States of');
insert into organisations_schema.countries(country_code, name) VALUES ('FO','Faroe Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('FR','France');
insert into organisations_schema.countries(country_code, name) VALUES ('FX','France, Metropolitan');
insert into organisations_schema.countries(country_code, name) VALUES ('GA','Gabon');
insert into organisations_schema.countries(country_code, name) VALUES ('GB','United Kingdom');
insert into organisations_schema.countries(country_code, name) VALUES ('GD','Grenada');
insert into organisations_schema.countries(country_code, name) VALUES ('GE','Georgia');
insert into organisations_schema.countries(country_code, name) VALUES ('GF','French Guiana');
insert into organisations_schema.countries(country_code, name) VALUES ('GH','Ghana');
insert into organisations_schema.countries(country_code, name) VALUES ('GI','Gibraltar');
insert into organisations_schema.countries(country_code, name) VALUES ('GL','Greenland');
insert into organisations_schema.countries(country_code, name) VALUES ('GM','Gambia');
insert into organisations_schema.countries(country_code, name) VALUES ('GN','Guinea');
insert into organisations_schema.countries(country_code, name) VALUES ('GP','Guadeloupe');
insert into organisations_schema.countries(country_code, name) VALUES ('GQ','Equatorial Guinea');
insert into organisations_schema.countries(country_code, name) VALUES ('GR','Greece');
insert into organisations_schema.countries(country_code, name) VALUES ('GS','South Georgia South Sandwich Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('GT','Guatemala');
insert into organisations_schema.countries(country_code, name) VALUES ('GU','Guam');
insert into organisations_schema.countries(country_code, name) VALUES ('GW','Guinea-Bissau');
insert into organisations_schema.countries(country_code, name) VALUES ('GY','Guyana');
insert into organisations_schema.countries(country_code, name) VALUES ('HK','Hong Kong');
insert into organisations_schema.countries(country_code, name) VALUES ('HM','Heard and Mc Donald Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('HN','Honduras');
insert into organisations_schema.countries(country_code, name) VALUES ('HR','Croatia (Hrvatska)');
insert into organisations_schema.countries(country_code, name) VALUES ('HT','Haiti');
insert into organisations_schema.countries(country_code, name) VALUES ('HU','Hungary');
insert into organisations_schema.countries(country_code, name) VALUES ('ID','Indonesia');
insert into organisations_schema.countries(country_code, name) VALUES ('IE','Ireland');
insert into organisations_schema.countries(country_code, name) VALUES ('IL','Israel');
insert into organisations_schema.countries(country_code, name) VALUES ('IN','India');
insert into organisations_schema.countries(country_code, name) VALUES ('IO','British lndian Ocean Territory');
insert into organisations_schema.countries(country_code, name) VALUES ('IQ','Iraq');
insert into organisations_schema.countries(country_code, name) VALUES ('IR','Iran (Islamic Republic of)');
insert into organisations_schema.countries(country_code, name) VALUES ('IS','Iceland');
insert into organisations_schema.countries(country_code, name) VALUES ('IT','Italy');
insert into organisations_schema.countries(country_code, name) VALUES ('JM','Jamaica');
insert into organisations_schema.countries(country_code, name) VALUES ('JO','Jordan');
insert into organisations_schema.countries(country_code, name) VALUES ('JP','Japan');
insert into organisations_schema.countries(country_code, name) VALUES ('KE','Kenya');
insert into organisations_schema.countries(country_code, name) VALUES ('KG','Kyrgyzstan');
insert into organisations_schema.countries(country_code, name) VALUES ('KH','Cambodia');
insert into organisations_schema.countries(country_code, name) VALUES ('KI','Kiribati');
insert into organisations_schema.countries(country_code, name) VALUES ('KM','Comoros');
insert into organisations_schema.countries(country_code, name) VALUES ('KN','Saint Kitts and Nevis');
insert into organisations_schema.countries(country_code, name) VALUES ('KR','Korea, Republic of');
insert into organisations_schema.countries(country_code, name) VALUES ('KW','Kuwait');
insert into organisations_schema.countries(country_code, name) VALUES ('KY','Cayman Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('KZ','Kazakhstan');
insert into organisations_schema.countries(country_code, name) VALUES ('LB','Lebanon');
insert into organisations_schema.countries(country_code, name) VALUES ('LC','Saint Lucia');
insert into organisations_schema.countries(country_code, name) VALUES ('LI','Liechtenstein');
insert into organisations_schema.countries(country_code, name) VALUES ('LK','Sri Lanka');
insert into organisations_schema.countries(country_code, name) VALUES ('LR','Liberia');
insert into organisations_schema.countries(country_code, name) VALUES ('LS','Lesotho');
insert into organisations_schema.countries(country_code, name) VALUES ('LT','Lithuania');
insert into organisations_schema.countries(country_code, name) VALUES ('LU','Luxembourg');
insert into organisations_schema.countries(country_code, name) VALUES ('LV','Latvia');
insert into organisations_schema.countries(country_code, name) VALUES ('LY','Libyan Arab Jamahiriya');
insert into organisations_schema.countries(country_code, name) VALUES ('MA','Morocco');
insert into organisations_schema.countries(country_code, name) VALUES ('MC','Monaco');
insert into organisations_schema.countries(country_code, name) VALUES ('MD','Moldova, Republic of');
insert into organisations_schema.countries(country_code, name) VALUES ('ME','Montenegro');
insert into organisations_schema.countries(country_code, name) VALUES ('MG','Madagascar');
insert into organisations_schema.countries(country_code, name) VALUES ('MH','Marshall Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('MK','Macedonia');
insert into organisations_schema.countries(country_code, name) VALUES ('ML','Mali');
insert into organisations_schema.countries(country_code, name) VALUES ('MM','Myanmar');
insert into organisations_schema.countries(country_code, name) VALUES ('MN','Mongolia');
insert into organisations_schema.countries(country_code, name) VALUES ('MO','Macau');
insert into organisations_schema.countries(country_code, name) VALUES ('MP','Northern Mariana Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('MQ','Martinique');
insert into organisations_schema.countries(country_code, name) VALUES ('MR','Mauritania');
insert into organisations_schema.countries(country_code, name) VALUES ('MS','Montserrat');
insert into organisations_schema.countries(country_code, name) VALUES ('MT','Malta');
insert into organisations_schema.countries(country_code, name) VALUES ('MU','Mauritius');
insert into organisations_schema.countries(country_code, name) VALUES ('MV','Maldives');
insert into organisations_schema.countries(country_code, name) VALUES ('MW','Malawi');
insert into organisations_schema.countries(country_code, name) VALUES ('MX','Mexico');
insert into organisations_schema.countries(country_code, name) VALUES ('MY','Malaysia');
insert into organisations_schema.countries(country_code, name) VALUES ('MZ','Mozambique');
insert into organisations_schema.countries(country_code, name) VALUES ('NA','Namibia');
insert into organisations_schema.countries(country_code, name) VALUES ('NC','New Caledonia');
insert into organisations_schema.countries(country_code, name) VALUES ('NE','Niger');
insert into organisations_schema.countries(country_code, name) VALUES ('NF','Norfork Island');
insert into organisations_schema.countries(country_code, name) VALUES ('NG','Nigeria');
insert into organisations_schema.countries(country_code, name) VALUES ('NI','Nicaragua');
insert into organisations_schema.countries(country_code, name) VALUES ('NL','Netherlands');
insert into organisations_schema.countries(country_code, name) VALUES ('NO','Norway');
insert into organisations_schema.countries(country_code, name) VALUES ('NP','Nepal');
insert into organisations_schema.countries(country_code, name) VALUES ('NR','Nauru');
insert into organisations_schema.countries(country_code, name) VALUES ('NU','Niue');
insert into organisations_schema.countries(country_code, name) VALUES ('NZ','New Zealand');
insert into organisations_schema.countries(country_code, name) VALUES ('OM','Oman');
insert into organisations_schema.countries(country_code, name) VALUES ('PA','Panama');
insert into organisations_schema.countries(country_code, name) VALUES ('PE','Peru');
insert into organisations_schema.countries(country_code, name) VALUES ('PF','French Polynesia');
insert into organisations_schema.countries(country_code, name) VALUES ('PG','Papua New Guinea');
insert into organisations_schema.countries(country_code, name) VALUES ('PH','Philippines');
insert into organisations_schema.countries(country_code, name) VALUES ('PK','Pakistan');
insert into organisations_schema.countries(country_code, name) VALUES ('PL','Poland');
insert into organisations_schema.countries(country_code, name) VALUES ('PM','St. Pierre and Miquelon');
insert into organisations_schema.countries(country_code, name) VALUES ('PN','Pitcairn');
insert into organisations_schema.countries(country_code, name) VALUES ('PR','Puerto Rico');
insert into organisations_schema.countries(country_code, name) VALUES ('PT','Portugal');
insert into organisations_schema.countries(country_code, name) VALUES ('PW','Palau');
insert into organisations_schema.countries(country_code, name) VALUES ('PY','Paraguay');
insert into organisations_schema.countries(country_code, name) VALUES ('QA','Qatar');
insert into organisations_schema.countries(country_code, name) VALUES ('RE','Reunion');
insert into organisations_schema.countries(country_code, name) VALUES ('RO','Romania');
insert into organisations_schema.countries(country_code, name) VALUES ('RS','Serbia');
insert into organisations_schema.countries(country_code, name) VALUES ('RU','Russian Federation');
insert into organisations_schema.countries(country_code, name) VALUES ('RW','Rwanda');
insert into organisations_schema.countries(country_code, name) VALUES ('SA','Saudi Arabia');
insert into organisations_schema.countries(country_code, name) VALUES ('SB','Solomon Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('SC','Seychelles');
insert into organisations_schema.countries(country_code, name) VALUES ('SD','Sudan');
insert into organisations_schema.countries(country_code, name) VALUES ('SE','Sweden');
insert into organisations_schema.countries(country_code, name) VALUES ('SG','Singapore');
insert into organisations_schema.countries(country_code, name) VALUES ('SH','St. Helena');
insert into organisations_schema.countries(country_code, name) VALUES ('SI','Slovenia');
insert into organisations_schema.countries(country_code, name) VALUES ('SJ','Svalbarn and Jan Mayen Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('SK','Slovakia');
insert into organisations_schema.countries(country_code, name) VALUES ('SL','Sierra Leone');
insert into organisations_schema.countries(country_code, name) VALUES ('SM','San Marino');
insert into organisations_schema.countries(country_code, name) VALUES ('SN','Senegal');
insert into organisations_schema.countries(country_code, name) VALUES ('SO','Somalia');
insert into organisations_schema.countries(country_code, name) VALUES ('SR','Suriname');
insert into organisations_schema.countries(country_code, name) VALUES ('ST','Sao Tome and Principe');
insert into organisations_schema.countries(country_code, name) VALUES ('SV','El Salvador');
insert into organisations_schema.countries(country_code, name) VALUES ('SY','Syrian Arab Republic');
insert into organisations_schema.countries(country_code, name) VALUES ('SZ','Swaziland');
insert into organisations_schema.countries(country_code, name) VALUES ('TC','Turks and Caicos Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('TD','Chad');
insert into organisations_schema.countries(country_code, name) VALUES ('TF','French Southern Territories');
insert into organisations_schema.countries(country_code, name) VALUES ('TG','Togo');
insert into organisations_schema.countries(country_code, name) VALUES ('TH','Thailand');
insert into organisations_schema.countries(country_code, name) VALUES ('TJ','Tajikistan');
insert into organisations_schema.countries(country_code, name) VALUES ('TK','Tokelau');
insert into organisations_schema.countries(country_code, name) VALUES ('TM','Turkmenistan');
insert into organisations_schema.countries(country_code, name) VALUES ('TN','Tunisia');
insert into organisations_schema.countries(country_code, name) VALUES ('TO','Tonga');
insert into organisations_schema.countries(country_code, name) VALUES ('TP','East Timor');
insert into organisations_schema.countries(country_code, name) VALUES ('TR','Turkey');
insert into organisations_schema.countries(country_code, name) VALUES ('TT','Trinidad and Tobago');
insert into organisations_schema.countries(country_code, name) VALUES ('TV','Tuvalu');
insert into organisations_schema.countries(country_code, name) VALUES ('TW','Taiwan');
insert into organisations_schema.countries(country_code, name) VALUES ('TY','Mayotte');
insert into organisations_schema.countries(country_code, name) VALUES ('TZ','Tanzania, United Republic of');
insert into organisations_schema.countries(country_code, name) VALUES ('UA','Ukraine');
insert into organisations_schema.countries(country_code, name) VALUES ('UG','Uganda');
insert into organisations_schema.countries(country_code, name) VALUES ('UM','United States minor outlying islands');
insert into organisations_schema.countries(country_code, name) VALUES ('US','United States');
insert into organisations_schema.countries(country_code, name) VALUES ('UY','Uruguay');
insert into organisations_schema.countries(country_code, name) VALUES ('UZ','Uzbekistan');
insert into organisations_schema.countries(country_code, name) VALUES ('VA','Vatican City State');
insert into organisations_schema.countries(country_code, name) VALUES ('VC','Saint Vincent and the Grenadines');
insert into organisations_schema.countries(country_code, name) VALUES ('VE','Venezuela');
insert into organisations_schema.countries(country_code, name) VALUES ('VG','Virgin Islands (British)');
insert into organisations_schema.countries(country_code, name) VALUES ('VI','Virgin Islands (U.S.)');
insert into organisations_schema.countries(country_code, name) VALUES ('VN','Vietnam');
insert into organisations_schema.countries(country_code, name) VALUES ('VU','Vanuatu');
insert into organisations_schema.countries(country_code, name) VALUES ('WF','Wallis and Futuna Islands');
insert into organisations_schema.countries(country_code, name) VALUES ('WS','Samoa');
insert into organisations_schema.countries(country_code, name) VALUES ('XK','Kosovo');
insert into organisations_schema.countries(country_code, name) VALUES ('YE','Yemen');
insert into organisations_schema.countries(country_code, name) VALUES ('YU','Yugoslavia');
insert into organisations_schema.countries(country_code, name) VALUES ('ZA','South Africa');
insert into organisations_schema.countries(country_code, name) VALUES ('ZM','Zambia');
insert into organisations_schema.countries(country_code, name) VALUES ('ZR','Zaire');
insert into organisations_schema.countries(country_code, name) VALUES ('ZW','Zimbabwe');
